// Core types for the LLM Gateway

export interface LLMProviderConfig {
  id: string
  name: string
  type: 'openai' | 'anthropic' | 'gemini' | 'lmstudio' | 'grok' | 'ollama' | 'openrouter' | 'groq'
  baseUrl: string
  apiKey?: string
  defaultModel: string
  availableModels: string[]
  maxContextWindow: number
  supportsStreaming: boolean
  supportsToolCalls: boolean
  supportsVision: boolean
}

export type ContentPart =
  | { type: 'text'; text: string }
  | { type: 'image_url'; image_url: { url: string } }
  | { type: 'audio_url'; audio_url: { url: string } }

export interface ChatMessage {
  role: 'system' | 'user' | 'assistant' | 'tool'
  content: string | ContentPart[]
  toolCalls?: ToolCall[]
  toolCallId?: string
  metadata?: Record<string, unknown>
}

export interface ToolCall {
  id: string
  type: 'function'
  function: {
    name: string
    arguments: string // JSON string
  }
  /** Gemini thought signature — must be echoed back for thinking models */
  thoughtSignature?: string
}

export interface ToolDefinition {
  name: string
  description: string
  parameters: Record<string, unknown> // JSON Schema
  timeout: number
  execute: (params: unknown) => Promise<ToolResult>
}

export interface ToolResult {
  success: boolean
  output: string
  error?: string
  /** File-path URLs for UI display (e.g. /api/files?path=...) */
  images?: string[]
  /** Base64 data-URL images for LLM vision (e.g. data:image/png;base64,...) */
  imageDataUrls?: string[]
}

export interface CompletionRequest {
  messages: ChatMessage[]
  model?: string
  temperature?: number
  maxTokens?: number
  tools?: ToolDefinition[]
  stream?: boolean
  signal?: AbortSignal
}

export interface CompletionResponse {
  id: string
  content: string
  thinking?: string
  toolCalls?: ToolCall[]
  /** Base64 data-URL images generated by the model */
  images?: string[]
  usage: {
    promptTokens: number
    completionTokens: number
    totalTokens: number
  }
  model: string
  provider: string
  latencyMs: number
}

export interface StreamChunk {
  content?: string
  thinking?: string
  toolCalls?: ToolCall[]
  /** Base64 data-URL images generated by the model */
  images?: string[]
  done: boolean
  usage?: CompletionResponse['usage']
}

export abstract class BaseLLMProvider {
  abstract readonly config: LLMProviderConfig
  abstract complete(request: CompletionRequest): Promise<CompletionResponse>
  abstract streamComplete(
    request: CompletionRequest
  ): AsyncIterable<StreamChunk>
  abstract listModels(type?: 'llm' | 'embedding'): Promise<string[]>
  abstract testConnection(): Promise<boolean>

  protected formatToolsForProvider(
    tools: ToolDefinition[]
  ): Record<string, unknown>[] {
    return tools.map((t) => ({
      type: 'function',
      function: {
        name: t.name,
        description: t.description,
        parameters: t.parameters
      }
    }))
  }

  protected getTextContent(content: string | ContentPart[]): string {
    if (typeof content === 'string') return content
    return content
      .filter((p) => p.type === 'text')
      .map((p) => (p as { type: 'text'; text: string }).text)
      .join('')
  }
}
