<script setup lang="ts">
import { ref, computed } from 'vue'
import { Icon } from '@iconify/vue'

const props = defineProps<{
  summary: string
  compactedMessageCount: number
  model: string
  createdAt: number
}>()

const expanded = ref(false)

const isPending = computed(() => !props.summary)

const formattedDate = computed(() => {
  return new Date(props.createdAt).toLocaleString(undefined, {
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
})
</script>

<template>
  <div class="px-4 py-3">
    <div class="max-w-4xl mx-auto">
      <!-- Divider line with label -->
      <div class="flex items-center gap-3 mb-2">
        <div class="flex-1 h-px bg-amber-500/20" />
        <button
          class="flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium transition-all group
                 bg-amber-500/8 hover:bg-amber-500/15 border border-amber-500/20 hover:border-amber-500/35
                 text-amber-400/80 hover:text-amber-300 disabled:cursor-default disabled:hover:bg-amber-500/8 disabled:hover:text-amber-400/80"
          :disabled="isPending"
          @click="!isPending && (expanded = !expanded)"
        >
          <Icon
            v-if="isPending"
            icon="svg-spinners:ring-resize"
            class="w-3.5 h-3.5 shrink-0 text-amber-400"
          />
          <Icon
            v-else
            icon="lucide:archive"
            class="w-3.5 h-3.5 shrink-0"
          />
          <span v-if="isPending">Compacting conversation…</span>
          <template v-else>
            <span>Context compacted — {{ compactedMessageCount }} messages summarized</span>
            <span class="text-amber-500/50 font-normal ml-1">{{ formattedDate }}</span>
            <Icon
              icon="lucide:chevron-down"
              class="w-3 h-3 shrink-0 transition-transform"
              :class="{ 'rotate-180': expanded }"
            />
          </template>
        </button>
        <div class="flex-1 h-px bg-amber-500/20" />
      </div>

      <!-- Expanded summary -->
      <Transition
        enter-active-class="transition-all duration-200 ease-out"
        enter-from-class="opacity-0 -translate-y-1"
        enter-to-class="opacity-100 translate-y-0"
        leave-active-class="transition-all duration-150 ease-in"
        leave-from-class="opacity-100 translate-y-0"
        leave-to-class="opacity-0 -translate-y-1"
      >
        <div
          v-if="expanded && !isPending"
          class="mx-auto mt-1 rounded-xl border border-amber-500/15 bg-amber-500/5 overflow-hidden"
        >
          <div class="flex items-center justify-between px-4 py-2 border-b border-amber-500/10">
            <div class="flex items-center gap-2 text-xs text-amber-400/70">
              <Icon
                icon="lucide:sparkles"
                class="w-3.5 h-3.5"
              />
              <span>Summary generated by <span class="font-mono text-amber-300/80">{{ model }}</span></span>
            </div>
          </div>
          <div class="px-4 py-3 text-sm text-theme-300 leading-relaxed whitespace-pre-wrap max-h-96 overflow-y-auto">
            {{ summary }}
          </div>
        </div>
      </Transition>
    </div>
  </div>
</template>
