<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { Icon } from '@iconify/vue'
import { api } from '../api/client'
import type { ActivityArtifact, ActivityItem } from '../api/types'
import ArtifactPreviewModal from '../components/shared/ArtifactPreviewModal.vue'

type ArtifactFilter = 'all' | ActivityArtifact['kind']

interface ArtifactEntry {
  id: string
  artifact: ActivityArtifact
  createdAt: number
  agentName: string | null
  conversationTitle: string
  conversationId: string | null
}

const activityItems = ref<ActivityItem[]>([])
const selectedFilter = ref<ArtifactFilter>('all')
const selectedEntry = ref<ArtifactEntry | null>(null)
const searchQuery = ref('')
const loading = ref(true)
const loadingMore = ref(false)
const hasMore = ref(false)
const error = ref('')
const PAGE_SIZE = 60
let searchTimer: ReturnType<typeof setTimeout> | undefined
let loadGeneration = 0

const filterOptions: { value: ArtifactFilter; label: string; icon: string }[] = [
  { value: 'all', label: 'All', icon: 'lucide:shapes' },
  { value: 'image', label: 'Images', icon: 'lucide:image' },
  { value: 'video', label: 'Videos', icon: 'lucide:film' },
  { value: 'audio', label: 'Audio', icon: 'lucide:audio-lines' },
  { value: 'file', label: 'Documents', icon: 'lucide:file-text' },
]

const allEntries = computed<ArtifactEntry[]>(() => {
  const entries: ArtifactEntry[] = []
  const seen = new Set<string>()

  for (const item of activityItems.value) {
    for (const [index, artifact] of (item.artifacts || []).entries()) {
      if (seen.has(artifact.href)) continue
      seen.add(artifact.href)
      entries.push({
        id: `${item.id}:${index}`,
        artifact,
        createdAt: item.createdAt,
        agentName: item.agentName,
        conversationTitle: item.description,
        conversationId: item.conversationId,
      })
    }
  }
  return entries
})

const visibleEntries = computed(() => selectedFilter.value === 'all'
  ? allEntries.value
  : allEntries.value.filter((entry) => entry.artifact.kind === selectedFilter.value))

const emptyTitle = computed(() => {
  if (searchQuery.value) return 'No matching artifacts'
  if (selectedFilter.value === 'all') return 'No artifacts yet'
  return `No ${filterOptions.find((option) => option.value === selectedFilter.value)?.label.toLowerCase() || 'artifacts'} yet`
})

const emptyDescription = computed(() => {
  if (searchQuery.value) return 'Try a different search or artifact type.'
  if (selectedFilter.value !== 'all') {
    return hasMore.value
      ? 'Load more results to keep looking through your workspace history.'
      : 'Generated output of this type will appear here.'
  }
  return 'Images, videos, audio, and files generated by your AI will appear here.'
})

function filterCount(filter: ArtifactFilter): number {
  if (filter === 'all') return allEntries.value.length
  return allEntries.value.filter((entry) => entry.artifact.kind === filter).length
}

function artifactIcon(kind: ActivityArtifact['kind']): string {
  if (kind === 'image') return 'lucide:image'
  if (kind === 'video') return 'lucide:film'
  if (kind === 'audio') return 'lucide:audio-lines'
  return 'lucide:file-text'
}

function artifactTypeLabel(artifact: ActivityArtifact): string {
  if (artifact.kind === 'file') return artifact.ext || 'Document'
  return artifact.kind
}

function formatDate(timestamp: number): string {
  const date = new Date(timestamp)
  const today = new Date()
  if (date.toDateString() === today.toDateString()) {
    return date.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })
  }
  return date.toLocaleDateString(undefined, {
    month: 'short',
    day: 'numeric',
    year: date.getFullYear() === today.getFullYear() ? undefined : 'numeric',
  })
}

async function loadArtifacts(reset = false): Promise<void> {
  if (!reset && (loading.value || loadingMore.value || !hasMore.value)) return
  const generation = reset ? ++loadGeneration : loadGeneration
  const offset = reset ? 0 : activityItems.value.length

  if (reset) {
    loading.value = true
    hasMore.value = false
  }
  else loadingMore.value = true
  error.value = ''

  try {
    const response = await api.activity.list({
      limit: PAGE_SIZE,
      offset,
      types: ['artifact'],
      search: searchQuery.value,
    })
    if (generation !== loadGeneration) return
    activityItems.value = reset ? response.items : [...activityItems.value, ...response.items]
    hasMore.value = Boolean(response.hasMore)
  } catch (err) {
    if (generation !== loadGeneration) return
    error.value = err instanceof Error ? err.message : 'Could not load artifacts.'
    if (reset) {
      activityItems.value = []
      hasMore.value = false
    }
  } finally {
    if (generation === loadGeneration) {
      loading.value = false
      loadingMore.value = false
    }
  }
}

function handleScroll(event: Event): void {
  const element = event.currentTarget as HTMLElement
  if (element.scrollHeight - element.scrollTop - element.clientHeight < 500) {
    void loadArtifacts()
  }
}

function clearSearch(): void {
  searchQuery.value = ''
}

watch(searchQuery, () => {
  clearTimeout(searchTimer)
  searchTimer = setTimeout(() => void loadArtifacts(true), 250)
})

onMounted(() => void loadArtifacts(true))
onUnmounted(() => clearTimeout(searchTimer))
</script>

<template>
  <div
    class="h-full overflow-y-auto"
    @scroll="handleScroll"
  >
    <div class="mx-auto max-w-7xl px-5 py-7 md:px-8 md:py-9">
      <header class="mb-7 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <div class="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-accent-400">
            <Icon
              icon="lucide:sparkles"
              class="h-3.5 w-3.5"
            />
            AI output library
          </div>
          <h1 class="text-2xl font-bold text-theme-100 md:text-3xl">
            Artifacts
          </h1>
          <p class="mt-1.5 max-w-xl text-sm leading-6 text-theme-500">
            Browse images, videos, audio, and documents generated across your workspace.
          </p>
        </div>

        <div class="flex w-full items-center gap-2 lg:w-auto">
          <label class="relative min-w-0 flex-1 lg:w-80 lg:flex-none">
            <span class="sr-only">Search artifacts</span>
            <Icon
              icon="lucide:search"
              class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-theme-500"
            />
            <input
              v-model="searchQuery"
              type="search"
              placeholder="Search files, agents, or conversations"
              class="h-10 w-full rounded-xl border border-theme-700 bg-theme-950/70 pl-9 pr-9 text-sm text-theme-200 outline-none transition placeholder:text-theme-600 focus:border-accent-500/60 focus:ring-2 focus:ring-accent-500/10"
            >
            <button
              v-if="searchQuery"
              type="button"
              aria-label="Clear search"
              class="absolute right-2.5 top-1/2 -translate-y-1/2 rounded p-1 text-theme-500 hover:text-theme-200"
              @click="clearSearch"
            >
              <Icon
                icon="lucide:x"
                class="h-3.5 w-3.5"
              />
            </button>
          </label>
          <button
            type="button"
            title="Refresh artifacts"
            aria-label="Refresh artifacts"
            class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-theme-700 bg-theme-950/70 text-theme-400 transition hover:border-theme-600 hover:text-theme-100"
            :disabled="loading"
            @click="loadArtifacts(true)"
          >
            <Icon
              icon="lucide:refresh-cw"
              class="h-4 w-4"
              :class="{ 'animate-spin': loading }"
            />
          </button>
        </div>
      </header>

      <div class="mb-6 flex items-center gap-2 overflow-x-auto pb-1">
        <button
          v-for="option in filterOptions"
          :key="option.value"
          type="button"
          class="inline-flex shrink-0 items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-medium transition"
          :class="selectedFilter === option.value
            ? 'border-accent-500/50 bg-accent-500/15 text-accent-200'
            : 'border-theme-700 bg-theme-950/50 text-theme-400 hover:border-theme-600 hover:text-theme-200'"
          @click="selectedFilter = option.value"
        >
          <Icon
            :icon="option.icon"
            class="h-3.5 w-3.5"
          />
          {{ option.label }}
          <span class="rounded-full bg-black/15 px-1.5 py-0.5 text-[10px]">{{ filterCount(option.value) }}</span>
        </button>
      </div>

      <div
        v-if="loading"
        class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4"
      >
        <div
          v-for="index in 8"
          :key="index"
          class="overflow-hidden rounded-2xl border border-theme-800 bg-theme-950/40"
        >
          <div class="aspect-4/3 animate-pulse bg-theme-800/60" />
          <div class="space-y-2 p-4">
            <div class="h-3 w-2/3 animate-pulse rounded bg-theme-800" />
            <div class="h-2.5 w-1/2 animate-pulse rounded bg-theme-800/70" />
          </div>
        </div>
      </div>

      <div
        v-else-if="error"
        class="flex min-h-80 flex-col items-center justify-center rounded-2xl border border-red-500/20 bg-red-500/5 px-6 text-center"
      >
        <Icon
          icon="lucide:triangle-alert"
          class="mb-3 h-8 w-8 text-red-400"
        />
        <p class="font-medium text-theme-200">
          Couldn't load artifacts
        </p>
        <p class="mt-1 max-w-md text-sm text-theme-500">
          {{ error }}
        </p>
        <button
          type="button"
          class="mt-4 rounded-lg bg-theme-800 px-4 py-2 text-sm text-theme-200 hover:bg-theme-700"
          @click="loadArtifacts(true)"
        >
          Try again
        </button>
      </div>

      <div
        v-else-if="!visibleEntries.length"
        class="flex min-h-96 flex-col items-center justify-center rounded-2xl border border-dashed border-theme-700 bg-theme-950/25 px-6 text-center"
      >
        <div class="mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-theme-800/70 text-theme-500">
          <Icon
            :icon="searchQuery ? 'lucide:search-x' : 'lucide:shapes'"
            class="h-7 w-7"
          />
        </div>
        <p class="font-semibold text-theme-200">
          {{ emptyTitle }}
        </p>
        <p class="mt-1 max-w-sm text-sm leading-6 text-theme-500">
          {{ emptyDescription }}
        </p>
      </div>

      <div
        v-else
        class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4"
      >
        <button
          v-for="entry in visibleEntries"
          :key="entry.id"
          type="button"
          class="group overflow-hidden rounded-2xl border border-theme-800 bg-theme-950/45 text-left shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-theme-600 hover:shadow-xl hover:shadow-black/15 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-500/60"
          @click="selectedEntry = entry"
        >
          <div class="relative flex aspect-4/3 items-center justify-center overflow-hidden bg-theme-950">
            <img
              v-if="entry.artifact.kind === 'image'"
              :src="entry.artifact.href"
              :alt="entry.artifact.label"
              loading="lazy"
              class="h-full w-full object-cover transition duration-300 group-hover:scale-[1.025]"
            >
            <video
              v-else-if="entry.artifact.kind === 'video'"
              :src="entry.artifact.href"
              muted
              playsinline
              preload="metadata"
              class="h-full w-full object-cover"
            />
            <div
              v-else
              class="flex flex-col items-center gap-3 text-theme-500"
            >
              <div class="flex h-16 w-16 items-center justify-center rounded-2xl bg-theme-800/80 ring-1 ring-theme-700/70 transition group-hover:text-accent-300">
                <Icon
                  :icon="artifactIcon(entry.artifact.kind)"
                  class="h-7 w-7"
                />
              </div>
              <span class="text-[11px] font-bold uppercase tracking-wider text-theme-600">{{ artifactTypeLabel(entry.artifact) }}</span>
            </div>
            <span class="absolute left-3 top-3 rounded-md border border-white/10 bg-black/55 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-white/85 backdrop-blur-sm">
              {{ artifactTypeLabel(entry.artifact) }}
            </span>
            <span class="absolute bottom-3 right-3 flex h-9 w-9 translate-y-1 items-center justify-center rounded-full bg-black/65 text-white opacity-0 shadow-lg backdrop-blur-sm transition group-hover:translate-y-0 group-hover:opacity-100">
              <Icon
                icon="lucide:maximize-2"
                class="h-4 w-4"
              />
            </span>
          </div>

          <div class="p-4">
            <p
              class="truncate text-sm font-semibold text-theme-200"
              :title="entry.artifact.label"
            >
              {{ entry.artifact.label }}
            </p>
            <div class="mt-2 flex items-center justify-between gap-3 text-[11px] text-theme-500">
              <span class="min-w-0 truncate">{{ entry.agentName || 'AI assistant' }}</span>
              <span class="shrink-0">{{ formatDate(entry.createdAt) }}</span>
            </div>
          </div>
        </button>
      </div>

      <div
        v-if="loadingMore"
        class="flex items-center justify-center gap-2 py-8 text-sm text-theme-500"
      >
        <Icon
          icon="lucide:loader-2"
          class="h-4 w-4 animate-spin"
        />
        Loading more artifacts…
      </div>
      <div
        v-else-if="hasMore"
        class="flex justify-center py-8"
      >
        <button
          type="button"
          class="rounded-xl border border-theme-700 bg-theme-950/50 px-4 py-2 text-sm text-theme-300 hover:border-theme-600 hover:text-theme-100"
          @click="loadArtifacts()"
        >
          Load more
        </button>
      </div>
    </div>

    <ArtifactPreviewModal
      :artifact="selectedEntry?.artifact || null"
      :created-at="selectedEntry?.createdAt"
      :agent-name="selectedEntry?.agentName"
      :conversation-title="selectedEntry?.conversationTitle"
      :conversation-id="selectedEntry?.conversationId"
      @close="selectedEntry = null"
    />
  </div>
</template>
