<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Icon } from '@iconify/vue'
import { api } from '../api/client'
import type { ActivityArtifact, ActivityItem, ConversationUpload } from '../api/types'
import LibraryPreviewModal from '../components/shared/LibraryPreviewModal.vue'
import TabBar, { type TabDef } from '../components/shared/TabBar.vue'

type LibraryPanel = 'generated' | 'uploads'
type LibraryFilter = 'all' | ActivityArtifact['kind']
type LibraryViewMode = 'grid' | 'list'

interface LibraryEntry {
  id: string
  artifact: ActivityArtifact
  createdAt: number
  agentName: string | null
  conversationTitle: string
  conversationId: string | null
  sizeBytes?: number
  chunkCount?: number
}

const sections = [
  {
    id: 'generated',
    path: '/library/generated',
    label: 'Generated',
    description: 'Browse images, videos, audio, and documents generated across your workspace.',
    icon: 'lucide:sparkles',
  },
  {
    id: 'uploads',
    path: '/library/uploads',
    label: 'Uploads',
    description: 'Browse durable copies of documents attached to your conversations.',
    icon: 'lucide:paperclip',
  },
] as const

const tabs: TabDef<LibraryPanel>[] = sections.map((section) => ({
  value: section.id,
  label: section.label,
  icon: section.icon,
}))

const route = useRoute()
const router = useRouter()
const activePanel = ref<LibraryPanel>('generated')
const activityItems = ref<ActivityItem[]>([])
const uploadItems = ref<ConversationUpload[]>([])
const selectedFilter = ref<LibraryFilter>('all')
const viewMode = ref<LibraryViewMode>('grid')
const selectedEntry = ref<LibraryEntry | null>(null)
const searchQuery = ref('')
const loading = ref(true)
const loadingMore = ref(false)
const hasMore = ref(false)
const error = ref('')
const PAGE_SIZE = 60
let searchTimer: ReturnType<typeof setTimeout> | undefined
let loadGeneration = 0

const filterOptions: { value: LibraryFilter; label: string; icon: string }[] = [
  { value: 'all', label: 'All', icon: 'lucide:shapes' },
  { value: 'image', label: 'Images', icon: 'lucide:image' },
  { value: 'video', label: 'Videos', icon: 'lucide:film' },
  { value: 'audio', label: 'Audio', icon: 'lucide:audio-lines' },
  { value: 'file', label: 'Documents', icon: 'lucide:file-text' },
]

const activeSection = computed(() => sections.find((section) => section.id === activePanel.value) || sections[0])

const generatedEntries = computed<LibraryEntry[]>(() => {
  const entries: LibraryEntry[] = []
  const seen = new Set<string>()

  for (const item of activityItems.value) {
    for (const [index, artifact] of (item.artifacts || []).entries()) {
      if (seen.has(artifact.href)) continue
      seen.add(artifact.href)
      entries.push({
        id: `${item.id}:${index}`,
        artifact,
        createdAt: item.createdAt,
        agentName: item.agentName,
        conversationTitle: item.description,
        conversationId: item.conversationId,
      })
    }
  }
  return entries
})

const uploads = computed<LibraryEntry[]>(() => uploadItems.value.map((upload) => ({
  id: upload.id,
  artifact: {
    href: upload.href,
    label: upload.name,
    kind: 'file',
    ext: upload.ext,
  },
  createdAt: upload.createdAt,
  agentName: upload.agentName,
  conversationTitle: upload.conversationTitle,
  conversationId: upload.conversationId,
  sizeBytes: upload.sizeBytes,
  chunkCount: upload.chunkCount,
})))

const visibleEntries = computed(() => {
  if (activePanel.value === 'uploads') return uploads.value
  return selectedFilter.value === 'all'
    ? generatedEntries.value
    : generatedEntries.value.filter((entry) => entry.artifact.kind === selectedFilter.value)
})

const emptyTitle = computed(() => {
  if (searchQuery.value) return activePanel.value === 'uploads' ? 'No matching uploads' : 'No matching generated files'
  if (activePanel.value === 'uploads') return 'No uploads yet'
  if (selectedFilter.value === 'all') return 'No generated files yet'
  return `No ${filterOptions.find((option) => option.value === selectedFilter.value)?.label.toLowerCase() || 'generated files'} yet`
})

const emptyDescription = computed(() => {
  if (searchQuery.value) return `Try a different search${activePanel.value === 'generated' ? ' or file type' : ''}.`
  if (activePanel.value === 'uploads') return 'Documents attached to chat messages will appear here and remain available for edits and retries.'
  if (selectedFilter.value !== 'all') {
    return hasMore.value
      ? 'Load more results to keep looking through your workspace history.'
      : 'Generated output of this type will appear here.'
  }
  return 'Images, videos, audio, and files generated by your AI will appear here.'
})

function filterCount(filter: LibraryFilter): number {
  if (filter === 'all') return generatedEntries.value.length
  return generatedEntries.value.filter((entry) => entry.artifact.kind === filter).length
}

function artifactIcon(kind: ActivityArtifact['kind']): string {
  if (kind === 'image') return 'lucide:image'
  if (kind === 'video') return 'lucide:film'
  if (kind === 'audio') return 'lucide:audio-lines'
  return 'lucide:file-text'
}

function artifactTypeLabel(artifact: ActivityArtifact): string {
  if (artifact.kind === 'file') return artifact.ext || 'Document'
  return artifact.kind
}

function formatDate(timestamp: number): string {
  const date = new Date(timestamp)
  const today = new Date()
  if (date.toDateString() === today.toDateString()) {
    return date.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })
  }
  return date.toLocaleDateString(undefined, {
    month: 'short',
    day: 'numeric',
    year: date.getFullYear() === today.getFullYear() ? undefined : 'numeric',
  })
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(bytes < 10 * 1024 ? 1 : 0)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(bytes < 10 * 1024 * 1024 ? 1 : 0)} MB`
}

async function loadEntries(reset = false): Promise<void> {
  if (!reset && (loading.value || loadingMore.value || !hasMore.value)) return
  const generation = reset ? ++loadGeneration : loadGeneration
  const offset = reset
    ? 0
    : activePanel.value === 'uploads' ? uploadItems.value.length : activityItems.value.length

  if (reset) {
    loading.value = true
    hasMore.value = false
  } else {
    loadingMore.value = true
  }
  error.value = ''

  try {
    if (activePanel.value === 'uploads') {
      const response = await api.chat.listUploads(PAGE_SIZE, offset, searchQuery.value)
      if (generation !== loadGeneration) return
      uploadItems.value = reset ? response.items : [...uploadItems.value, ...response.items]
      hasMore.value = uploadItems.value.length < response.total
    } else {
      const response = await api.activity.list({
        limit: PAGE_SIZE,
        offset,
        types: ['artifact'],
        search: searchQuery.value,
      })
      if (generation !== loadGeneration) return
      activityItems.value = reset ? response.items : [...activityItems.value, ...response.items]
      hasMore.value = Boolean(response.hasMore)
    }
  } catch (err) {
    if (generation !== loadGeneration) return
    error.value = err instanceof Error ? err.message : `Could not load ${activePanel.value}.`
    if (reset) {
      if (activePanel.value === 'uploads') uploadItems.value = []
      else activityItems.value = []
      hasMore.value = false
    }
  } finally {
    if (generation === loadGeneration) {
      loading.value = false
      loadingMore.value = false
    }
  }
}

function selectPanel(panel: LibraryPanel): void {
  const section = sections.find((candidate) => candidate.id === panel)
  if (section && route.path !== section.path) void router.push(section.path)
}

function handleScroll(event: Event): void {
  const element = event.currentTarget as HTMLElement
  if (element.scrollHeight - element.scrollTop - element.clientHeight < 500) {
    void loadEntries()
  }
}

function clearSearch(): void {
  searchQuery.value = ''
}

watch(
  () => route.params.section,
  (sectionParam) => {
    const section = Array.isArray(sectionParam) ? sectionParam[0] : sectionParam
    activePanel.value = section === 'uploads' ? 'uploads' : 'generated'
    selectedEntry.value = null
    void loadEntries(true)
  },
  { immediate: true },
)

watch(searchQuery, () => {
  clearTimeout(searchTimer)
  searchTimer = setTimeout(() => void loadEntries(true), 250)
})

onUnmounted(() => clearTimeout(searchTimer))
</script>

<template>
  <div
    class="h-full overflow-y-auto"
    @scroll="handleScroll"
  >
    <header class="sticky top-0 z-10 border-b border-theme-800/60 bg-theme-950/95 px-5 pt-5 backdrop-blur-sm md:px-8 md:pt-6">
      <div class="mx-auto flex max-w-7xl flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div class="min-w-0">
          <h1 class="text-2xl font-bold text-theme-100">
            Library
          </h1>
          <p class="mt-1 text-sm leading-relaxed text-theme-500">
            {{ activeSection.description }}
          </p>
        </div>

        <div class="flex w-full shrink-0 items-center gap-2 sm:w-auto">
          <label class="relative min-w-0 flex-1 sm:w-80 sm:flex-none">
            <span class="sr-only">Search {{ activePanel === 'uploads' ? 'uploads' : 'generated files' }}</span>
            <Icon
              icon="lucide:search"
              class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-theme-500"
            />
            <input
              v-model="searchQuery"
              type="search"
              :placeholder="activePanel === 'uploads' ? 'Search uploads or conversations' : 'Search files, agents, or conversations'"
              class="h-10 w-full rounded-xl border border-theme-700 bg-theme-950/70 pl-9 pr-9 text-sm text-theme-200 outline-none transition placeholder:text-theme-600 focus:border-accent-500/60 focus:ring-2 focus:ring-accent-500/10"
            >
            <button
              v-if="searchQuery"
              type="button"
              aria-label="Clear search"
              class="absolute right-2.5 top-1/2 -translate-y-1/2 rounded p-1 text-theme-500 hover:text-theme-200"
              @click="clearSearch"
            >
              <Icon
                icon="lucide:x"
                class="h-3.5 w-3.5"
              />
            </button>
          </label>
          <button
            type="button"
            :title="`Refresh ${activePanel}`"
            :aria-label="`Refresh ${activePanel}`"
            class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-theme-700 bg-theme-950/70 text-theme-400 transition hover:border-theme-600 hover:text-theme-100"
            :disabled="loading"
            @click="loadEntries(true)"
          >
            <Icon
              icon="lucide:refresh-cw"
              class="h-4 w-4"
              :class="{ 'animate-spin': loading }"
            />
          </button>
        </div>
      </div>

      <TabBar
        :model-value="activePanel"
        :tabs="tabs"
        class="mx-auto mt-4 max-w-7xl"
        @update:model-value="selectPanel"
      />
    </header>

    <div class="mx-auto max-w-7xl px-5 py-6 md:px-8">
      <div class="mb-6 flex items-center justify-between gap-3">
        <div
          v-if="activePanel === 'generated'"
          class="flex min-w-0 items-center gap-2 overflow-x-auto pb-1"
        >
          <button
            v-for="option in filterOptions"
            :key="option.value"
            type="button"
            class="library-filter-button inline-flex shrink-0 items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-medium transition"
            :aria-pressed="selectedFilter === option.value"
            :class="selectedFilter === option.value
              ? 'border-accent-500/50 bg-accent-500/15 text-accent-200'
              : 'border-theme-700 bg-theme-950/50 text-theme-400 hover:border-theme-600 hover:text-theme-200'"
            @click="selectedFilter = option.value"
          >
            <Icon
              :icon="option.icon"
              class="h-3.5 w-3.5"
            />
            {{ option.label }}
            <span class="rounded-full bg-black/15 px-1.5 py-0.5 text-[10px]">{{ filterCount(option.value) }}</span>
          </button>
        </div>
        <div
          v-else
          class="flex min-w-0 items-center gap-2 text-xs text-theme-500"
        >
          <Icon
            icon="lucide:shield-check"
            class="h-4 w-4 shrink-0 text-accent-400"
          />
          <span>Stored copies used when messages are edited or retried</span>
        </div>

        <div
          class="flex shrink-0 items-center rounded-lg border border-theme-700 bg-theme-950/70 p-1"
          role="group"
          aria-label="Library view layout"
        >
          <button
            v-for="mode in ([
              { value: 'grid', label: 'Grid view', icon: 'lucide:grid-2x2' },
              { value: 'list', label: 'List view', icon: 'lucide:list' },
            ] as const)"
            :key="mode.value"
            type="button"
            :title="mode.label"
            :aria-label="mode.label"
            :aria-pressed="viewMode === mode.value"
            class="flex h-7 w-8 items-center justify-center rounded-md transition"
            :class="viewMode === mode.value
              ? 'bg-theme-700 text-theme-100 shadow-sm'
              : 'text-theme-500 hover:bg-theme-800/70 hover:text-theme-200'"
            @click="viewMode = mode.value"
          >
            <Icon
              :icon="mode.icon"
              class="h-3.5 w-3.5"
            />
          </button>
        </div>
      </div>

      <div
        v-if="loading"
        :class="viewMode === 'grid'
          ? 'grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4'
          : 'space-y-2'"
      >
        <div
          v-for="index in 8"
          :key="index"
          class="overflow-hidden border border-theme-800 bg-theme-950/40"
          :class="viewMode === 'grid' ? 'rounded-2xl' : 'flex h-24 rounded-xl'"
        >
          <div
            class="shrink-0 animate-pulse bg-theme-800/60"
            :class="viewMode === 'grid' ? 'aspect-4/3 w-full' : 'h-full w-24 sm:w-28'"
          />
          <div class="flex-1 space-y-2 p-4">
            <div class="h-3 w-2/3 animate-pulse rounded bg-theme-800" />
            <div class="h-2.5 w-1/2 animate-pulse rounded bg-theme-800/70" />
          </div>
        </div>
      </div>

      <div
        v-else-if="error"
        class="flex min-h-80 flex-col items-center justify-center rounded-2xl border border-red-500/20 bg-red-500/5 px-6 text-center"
      >
        <Icon
          icon="lucide:triangle-alert"
          class="mb-3 h-8 w-8 text-red-400"
        />
        <p class="font-medium text-theme-200">
          Couldn't load {{ activePanel === 'uploads' ? 'uploads' : 'generated files' }}
        </p>
        <p class="mt-1 max-w-md text-sm text-theme-500">
          {{ error }}
        </p>
        <button
          type="button"
          class="mt-4 rounded-lg bg-theme-800 px-4 py-2 text-sm text-theme-200 hover:bg-theme-700"
          @click="loadEntries(true)"
        >
          Try again
        </button>
      </div>

      <div
        v-else-if="!visibleEntries.length"
        class="flex min-h-96 flex-col items-center justify-center rounded-2xl border border-dashed border-theme-700 bg-theme-950/25 px-6 text-center"
      >
        <div class="mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-theme-800/70 text-theme-500">
          <Icon
            :icon="searchQuery ? 'lucide:search-x' : activePanel === 'uploads' ? 'lucide:paperclip' : 'lucide:shapes'"
            class="h-7 w-7"
          />
        </div>
        <p class="font-semibold text-theme-200">
          {{ emptyTitle }}
        </p>
        <p class="mt-1 max-w-sm text-sm leading-6 text-theme-500">
          {{ emptyDescription }}
        </p>
      </div>

      <div
        v-else
        :class="viewMode === 'grid'
          ? 'grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4'
          : 'space-y-2'"
      >
        <button
          v-for="entry in visibleEntries"
          :key="entry.id"
          type="button"
          class="group w-full overflow-hidden border border-theme-800 bg-theme-950/45 text-left shadow-sm transition duration-200 hover:border-theme-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-500/60"
          :class="viewMode === 'grid'
            ? 'rounded-2xl hover:-translate-y-0.5 hover:shadow-xl hover:shadow-black/15'
            : 'flex min-h-20 rounded-xl hover:bg-theme-900/60'"
          @click="selectedEntry = entry"
        >
          <div
            class="relative flex shrink-0 items-center justify-center overflow-hidden bg-theme-950"
            :class="viewMode === 'grid' ? 'aspect-4/3 w-full' : 'h-20 w-20 self-stretch sm:h-24 sm:w-28'"
          >
            <img
              v-if="entry.artifact.kind === 'image'"
              :src="entry.artifact.href"
              :alt="entry.artifact.label"
              loading="lazy"
              class="h-full w-full object-cover transition duration-300 group-hover:scale-[1.025]"
            >
            <video
              v-else-if="entry.artifact.kind === 'video'"
              :src="entry.artifact.href"
              muted
              playsinline
              preload="metadata"
              class="h-full w-full object-cover"
            />
            <div
              v-else
              class="flex flex-col items-center text-theme-500"
              :class="viewMode === 'grid' ? 'gap-3' : 'gap-1.5'"
            >
              <div
                class="flex items-center justify-center bg-theme-800/80 ring-1 ring-theme-700/70 transition group-hover:text-accent-300"
                :class="viewMode === 'grid' ? 'h-16 w-16 rounded-2xl' : 'h-10 w-10 rounded-xl'"
              >
                <Icon
                  :icon="artifactIcon(entry.artifact.kind)"
                  :class="viewMode === 'grid' ? 'h-7 w-7' : 'h-5 w-5'"
                />
              </div>
              <span
                v-if="viewMode === 'grid'"
                class="text-[11px] font-bold uppercase tracking-wider text-theme-600"
              >{{ artifactTypeLabel(entry.artifact) }}</span>
            </div>
            <span
              class="absolute rounded-md border border-white/10 bg-black/55 font-bold uppercase tracking-wider text-white/85 backdrop-blur-sm"
              :class="viewMode === 'grid' ? 'left-3 top-3 px-2 py-1 text-[10px]' : 'left-1.5 top-1.5 px-1.5 py-0.5 text-[8px]'"
            >
              {{ artifactTypeLabel(entry.artifact) }}
            </span>
            <span
              v-if="viewMode === 'grid'"
              class="absolute bottom-3 right-3 flex h-9 w-9 translate-y-1 items-center justify-center rounded-full bg-black/65 text-white opacity-0 shadow-lg backdrop-blur-sm transition group-hover:translate-y-0 group-hover:opacity-100"
            >
              <Icon
                icon="lucide:maximize-2"
                class="h-4 w-4"
              />
            </span>
          </div>

          <div
            class="min-w-0 flex-1 p-4"
            :class="{ 'flex flex-col justify-center': viewMode === 'list' }"
          >
            <p
              class="truncate text-sm font-semibold text-theme-200"
              :title="entry.artifact.label"
            >
              {{ entry.artifact.label }}
            </p>
            <p
              v-if="viewMode === 'list'"
              class="mt-1 truncate text-xs text-theme-500"
            >
              {{ entry.conversationTitle }}
            </p>
            <div class="mt-2 flex items-center justify-between gap-3 text-[11px] text-theme-500">
              <span class="min-w-0 truncate">
                {{ entry.agentName || (activePanel === 'uploads' ? 'Free Chat' : 'AI assistant') }}
                <template v-if="entry.sizeBytes != null"> · {{ formatBytes(entry.sizeBytes) }}</template>
              </span>
              <span class="shrink-0">{{ formatDate(entry.createdAt) }}</span>
            </div>
          </div>
        </button>
      </div>

      <div
        v-if="loadingMore"
        class="flex items-center justify-center gap-2 py-8 text-sm text-theme-500"
      >
        <Icon
          icon="lucide:loader-2"
          class="h-4 w-4 animate-spin"
        />
        Loading more {{ activePanel === 'uploads' ? 'uploads' : 'generated files' }}…
      </div>
      <div
        v-else-if="hasMore"
        class="flex justify-center py-8"
      >
        <button
          type="button"
          class="rounded-xl border border-theme-700 bg-theme-950/50 px-4 py-2 text-sm text-theme-300 hover:border-theme-600 hover:text-theme-100"
          @click="loadEntries()"
        >
          Load more
        </button>
      </div>
    </div>

    <LibraryPreviewModal
      :artifact="selectedEntry?.artifact || null"
      :created-at="selectedEntry?.createdAt"
      :agent-name="selectedEntry?.agentName"
      :conversation-title="selectedEntry?.conversationTitle"
      :conversation-id="selectedEntry?.conversationId"
      @close="selectedEntry = null"
    />
  </div>
</template>
